src/Entity/Chat.php
<?php

namespace App\Entity;

use App\Repository\ChatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatRepository::class)
 */
class Chat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="posts")
     */
    private $categorie;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $priority;

    /**
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="posts")
     */
    private $id_parent;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="id_parent", orphanRemoval=true)
     */
    private $posts;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getPriority(): ?bool
    {
        return $this->priority;
    }

    public function setPriority(?bool $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getIdParent(): ?self
    {
        return $this->id_parent;
    }

    public function setIdParent(?self $id_parent): self
    {
        $this->id_parent = $id_parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(self $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setIdParent($this);
        }

        return $this;
    }

    public function removePost(self $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getIdParent() === $this) {
                $post->setIdParent(null);
            }
        }

        return $this;
    }
}

templates/topic/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Éditer
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('js/script.js') }}" defer></script>
{% endblock %}
{% block body %}
	<main class="container">
		<div class="row">
			<section class="editor col-12 my-5">
				{{ form_start(formContent) }}
				{{ form_row(formContent.content) }}
				<button class="btn btn-block btn-success">Modifier</button>
				{{ form_row(formContent._token) }}
				{{ form_end(formContent, {'render_rest': false}) }}
			</section>
		</div>
	</main>
{% endblock %}

templates/topic/edit_topic.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Éditer
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('js/script.js') }}" defer></script>
{% endblock %}
{% block body %}
	<main class="container">
		<div class="row">
			<section class="editor col-12 my-5">
				{{ form_start(formContent) }}
				{{ form_row(formContent.title) }}
				{{ form_row(formContent.content) }}
				{{ form_row(formContent.categorie) }}

				{% if is_granted('ROLE_ADMIN') %}
					{{ form_row(formContent.priority) }}
				{% endif %}
            
				<button class="btn btn-block btn-success">Modifier</button>
				{{ form_end(formContent) }}
			</section>
		</div>
	</main>
{% endblock %}

templates/topic/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ topic.title }}
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('js/script.js') }}" defer></script>
{% endblock %}
{% block body %}
	<div id="topic" class="row no-gutters">

		<nav class="col-12 mt-3">
			<a href="{{ path("page_categorie", { id: topic.categorie.id }) }}">
				<i class="fas fa-arrow-left"></i>
				Retour à
				{{ topic.categorie.name }}</a>
		</nav>

		<h1 class="col-12 mb-3">{{ topic.title }}</h1>

		{# gestion du message de succès #}
		{% for message in app.flashes('success') %}
			<div class="alert alert-success col-12 px-3">{{ message }}</div>
		{% endfor %}

		{% for message in app.flashes('error') %}
			<div class="alert alert-danger col-12 px-3">{{ message }}</div>
		{% endfor %}

      {# Affichage du premier post du sujet, le "parent" #}
      <div class="col-12 card post-{{ topic.id }} mb-3">
         <div class="row no-gutters card-header align-items-center">
            <img src="{{ asset('images/avatars/'~ topic.user.avatar)|imagine_filter('profil') }}" alt="{{ topic.user.avatar }}" class="rounded col-1 img-fluid">
            <div class="col-9 pl-3">
            <p>Par {{ topic.user.username }} 
            le {{ topic.createdAt|date('d/m/Y à H:i') }}.</p>
            <hr>
            {% for group in topic.user.groups %}
               <span class="badge rounded-pill text-light"
                  style="background-color:{{ group.color }};">
                  {{ group.name }}
               </span>
            {% endfor %}
            </div>
            {% if app.user and ((topic.user.id is same as app.user.id) or is_granted('ROLE_ADMIN')) %}
            <div class="col-2 text-right">
               <a href="{{ path('edit_post', {id:topic.id}) }}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
               <a href="{{ path('delete_post', {id:topic.id}) }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
            </div>
            {% endif %}
         </div>
         <div class="p-3 card-body">
            <p class="text-justify">{{ topic.content|raw }}</p>
            {% if topic.updatedAt %}
               <p class="text-muted">Dernière édition : {{ topic.updatedAt|date('d/m/Y à H:i') }}.</p>
            {% endif %}
         </div>
      </div>

      {# Affichage des posts liés à leur parent #}
      {% for post in posts %}
      <div class="col-12 card post-{{ post.id }} mb-3">
         <div class="row no-gutters card-header align-items-center">
            <img src="{{ '/images/avatars/'~ post.user.avatar }}" alt="{{ post.user.username }}" class="rounded col-1">
            <div class="col-9 pl-3">
               <p>Par {{ post.user.username }} 
               le {{ post.createdAt|date('d/m/Y à H:i') }}.</p>
               <hr>
               {% for group in post.user.groups %}
                  <span class="badge rounded-pill text-light"
                     style="background-color:{{ group.color }};">
                     {{ group.name }}
                  </span>
               {% endfor %}
            </div>
            {% if app.user and ((topic.user.id is same as app.user.id) or is_granted('ROLE_ADMIN')) %}
            <div class="col-2 text-right">
               <a href="{{ path('edit_post', {id:post.id}) }}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
               <a href="{{ path('delete_post', {id:post.id}) }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
            </div>
            {% endif %}
         </div>
         <div class="p-3 card-body">
            <p class="text-justify">{{ post.content|raw }}</p>
            {% if post.updatedAt %}
               <p class="text-muted">Dernière édition : {{ post.updatedAt|date('d/m/Y à H:i') }}.</p>
            {% endif %}
         </div>
      </div>
      {% else %}
      <div class="col-12 text-muted">Aucune réponse pour le moment.</div>
      {% endfor %}

		{# Pagination pour les posts #}
		<div class="col-12">
			{{ knp_pagination_render(posts) }}
		</div>

		{% if app.user %}
			{# Editeur, visible uniquement aux connectés #}
			<div class="editor col-12 mt-2 mb-4">
				{{ form_start(formContent) }}
				{{ form_row(formContent.content) }}
				<button class="btn btn-block btn-dark">Ajouter</button>
				{{ form_row(formContent._token) }}
				{{ form_end(formContent, {'render_rest': false}) }}
			</div>
		{% else %}
			<p class="col-12 border my-5 p-3 text-center text-muted">Vous devez être connecté pour répondre à ce sujet.
				<a href="{{ path('app_login') }}">Connectez-vous</a>
				ou
				<a href="{{ path('app_register') }}">inscrivez-vous</a>.</p>
		{% endif %}

	</div>
   
   <!-- Trigger/Open The Modal -->

		<div id="myBtn" class="modal-header">
			<h1 id="ttchat">
				<i class="far fa-comments"></i>
			</h1>
		</div>
	<!-- The Modal -->
		<div
			id="myModal" class="modal">

			<!-- Modal content -->
			<div class="modal-content">
				<div class="modal-body">
					<section id="chat" class="col-12">

						<div>
							<span class="close">
								<i class="fas fa-times-circle"></i>
							</span>
							<a href="http://forum-nova.test/chat" target="_blank">
								<h1>
									<i class="far fa-comments"></i>
								</h1>
							</a>
							<div class="col-12 my-1">
								<div class="p-2" id="discussion"></div>
							</div>
							<div class="col-12 saisie">
								<div class="input-group">
									<input type="text" class="form-control" id="texte" placeholder="Entrez votre texte">
									<div class="input-group-append">
										<span class="input-group-text" id="valid">
											<i class="la la-check">
												<i class="fas fa-share"></i>
											</i>
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>

		</div>
	</div>
</div>
{% endblock %}

templates/topic/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Nouveau sujet
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('js/script.js') }}" defer></script>
{% endblock %}
{% block body %}
	<main class="container">
		<div class="row">
			<section class="editor col-12 my-5">
				{{ form_start(formContent) }}
				{{ form_row(formContent.title) }}
				{{ form_row(formContent.content) }}
				{{ form_row(formContent.categorie) }}

				{% if is_granted('ROLE_ADMIN') %}
					{{ form_row(formContent.priority) }}
				{% endif %}

				<button class="btn btn-block btn-success">Envoyer</button>
				{{ form_end(formContent) }}
			</section>
		</div>
	</main>
{% endblock %}